(require 'cask "~/.cask/cask.el")
(cask-initialize)
(require 'pallet)

(add-to-list 'load-path "~/.emacs.d/custom")

(load "00common-setup.el")
(load "01ruby.el")
(load "02auto-complete.el")
(load "03spartparens.el")
(load "04projectile.el")
(load "05highlight-indentation.el")
(load "06flyspell.el")
(load "07ido-vertical.el")
(load "08power-line.el")
(load "09smart-beginning-of-line.el")
(load "10linum-relative.el")
(load "11color-theme-railscasts.el")
(load "12yasnippet.el")
(load "13js2mode.el")
(load "14auto-indentation.el")
